databases:
  - name: possireports-db
    plan: free
    region: singapore

services:
  - type: web
    name: possireports
    env: python
    rootDir: new_portal
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 4 --timeout 120 app:app
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DATABASE_URL
        fromDatabase:
          name: possireports-db
          property: connectionString
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@possireports.in
      - key: ADMIN_PASSWORD
        value: "Admin@2026#Reset"
